AWSTemplateFormatVersion: '2010-09-09'
Description: MyEC2Instance
Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22 and HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-048d6ed8eabb546f1
      KeyName: demo
      SecurityGroupIds:
        - !Ref MySecurityGroup

      Tags:
        - Key: Name
          Value: Frist-EC2